;asm file containing the instructions and title screen data
;to be inflated into $4000

	opt h-	;disable writing atari header data
	org $4000       
	icl "../matosimi_macros.asx"
	;.align $4000
title_scroll

:20	dta d"                                "
	dta d" The hordes are coming! Wave    "
	dta d" after wave of goblins,         "
	dta d" skeletons, zombies, snakes,    "
	dta d" wizards and all manner of      "
	dta d" creatures from the nether      "
	dta d" dimensions are attacking our   "
	dta d" castle. It is up to you to     "
	dta d" save us from the onslaught     "
	dta d" using our defensive towers!    "
	dta d"                                "
	dta d" Enemies will emerge from the   " 
	dta d" portal and move along the path "
	dta d" to our castle. Place different "
	dta d" tower types that automatically "
	dta d" attack anything that gets      "
	dta d" within their range.            "       
	dta d"                                "
	dta d" Controls:                      "
	dta d" =========                      "
	dta d"^WASD"*,d" keys or joystick move     "
	dta d" your cursor.                   "
	dta d"                                "
	dta d"^Fire"*,d" or",d"^Return"*,d" shows build and "
	dta d" upgrade options of selected    "
	dta d" tower or vacant space.         "
	dta d"                                "
	dta d" Number keys ",d"^123"*,d" build a tower "
	dta d" of that type in a vacant space."
	dta d"                                "
	dta d"^U"*,d" upgrades an existing tower.  "
	dta d"                                "
	dta d"^Space"*,d" speeds the game up       "
	dta d" whilst held.                   "
	dta d"                                "
	dta d"^Start"*,d" +",d"^Select"*,d" +",d"^Option"*," Quit.  "
	dta d"                                "
	dta d" Towers:                        "
	dta d" =======                        "
	dta d" Each tower has various         "
	dta d" attributes which are shown in  "
	dta d" the build bar accessible by    "
	dta d"^Fire"*,d" or",d"^Return"*,d".                "
	dta d"                                "
	dta 0,65,66,67,d": Tower level (0-3).        "
	dta 0,68,69,70,d": Amount of physical damage "
	dta d"      each shot inflicts.       "
	dta 0,71,72,73,d": Amount of shield damage   "
	dta d"      each shot inflicts.       "
	dta 0,74,75,76,d": Tower range.              "
	dta 0,77,78,79,d": Rate of fire.             "
	dta 0,80,81,82,d": Cost of tower or upgrade. "
	dta d"                                "
	dta d" Build bar:                     "
	dta d" ==========                     "
	dta d" When an empty space is         "
	dta d" selected build bar shows       "
	dta d" information for all available  "
	dta d" towers. If a tower is selected "
	dta d" the current and upgrade values "
	dta d" are shown.                     "
	dta d"                                "
	dta d" Status columns:                "
	dta d" ===============                "
	dta d" The left column shows your     "
	dta d" lives, gold and score.         "
	dta d"                                "
	dta d" The right column shows the     "
	dta d" current health and shield of   "
	dta d" the enemy nearest the castle.  "
	dta d"                                "
	dta d" * is the number of enemies     "
	dta d" left to destroy.               "
	dta d"                                "
	dta d" Enemies:                       "
	dta d" ========                       "
	dta d" Each enemy has a starting      "
	dta d" strength and shield, values    "
	dta d" shown on bottom red enemy bar. "
	dta d"                                "
	dta d" If an enemy has a shield then  "
	dta d" any damage will be reduced by  "
	dta d" the shield amount.             "
	dta d"                                "
	dta d" Destroying an enemy gives you  "
	dta d" a little gold but letting one  "
	dta d" reach the castle will cost you "
	dta d" one life.                      "
	dta d"                                "
	dta d"   ...Good Luck!                " 
	dta d"                                "
	dta d"                                "
	dta d" Credits:                       "
	dta d" ========                       "
	dta d" Original BBC Micro code:       "
	dta d"                Chris Bradburne "
	dta d"                                "
	dta d" Original BBC Micro design:     "
	dta d"                    John Blythe "
	dta d"                                "
	dta d" Atari code and design:         "
	dta d"                 Martin Simecek "
	dta d"                                "
	dta d" Title screen:                  "
	dta d"                  Piotr Radecki "
	dta d"                                "
	dta d" Music:                         "
	dta d"                 Michal Radecki "
	dta d"                                "
	guard title_scroll+$1000 	;do not cross 1kB boundary
title_static
	dta d"                                "
	dta d"                                "
	dta d"       High score: 00000000     "
	dta d"   Enemies killed: 0%           "
	dta d"         Progress: 0%           "
	dta d"                                "
	dta d"                                "
	dta d"       Last score: 00000000     "
	dta d"   Enemies killed: 0%           "
	dta d"         Progress: 0%           "
	dta d"                                "
	dta d"                                "
	dta d"                                "
	dta d"                                "
	dta d"          Instructions          "
	dta d"              Play              "
	dta d"                                "
	dta d"                                "
	dta d"                                "
	dta d"   http://matosimi.atari.org    "
	dta d"                                "
title_end

.print "title_scroll: ",title_scroll
.print "title_static: ",title_static
.print "end: ",title_end
